repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.43.0 # Replace with the desired version of golangci-lint
    hooks:
      - id: golangci-lint
        args: [--config=.golangci.yml]
